{% set name = "esi-utils-geo" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esi-utils-geo-{{ version }}.tar.gz
  sha256: 921c925d2c18b394e99406de152abc83fe965bc29a0226f3882705c71f3fd432

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - pandas >=1.4.1
    - geopy >=2.1.0

test:
  imports:
    - esi_utils_geo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/esi-utils-geo/
  summary: USGS Earthquake Basic Geographic Utilities
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
